name: build-deploy-release

on:
  push:
    tags:
      - '\d+.\d+.\d+'

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 5.0
          mongodb-username: mongoroot
          mongodb-password: mongorootpassword
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Extract Project version
        id: project
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Build with Maven
        if:  ${{ !endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode -Prelease verify
      - name: Deploy package to repository
        if:  ${{ !endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        env:
          REPOUSER: ${{ secrets.repouser }}
          REPOPASS: ${{ secrets.repopass }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>quinimbus-snapshots</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server><server><id>quinimbus-releases</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -DskipTests -Prelease deploy
      - name: Create Release
        if:  ${{ !endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            modules/api/target/*.jar
            modules/cdi/target/*.jar
            modules/common/target/*.jar
            modules/core/target/*.jar
            modules/mongo/target/*.jar
            modules/repositories/target/*.jar