name: build-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 5.0
          mongodb-username: mongoroot
          mongodb-password: mongorootpassword
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Extract Project version
        id: project
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Build with Maven
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode --update-snapshots verify site
      - name: Deploy package to repository
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        env:
          REPOUSER: ${{ secrets.repouser }}
          REPOPASS: ${{ secrets.repopass }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>quinimbus-snapshots</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server><server><id>quinimbus-releases</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -DskipTests deploy
      - name: Deploy apidocs
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        uses: balta3/action-upload-webdav@main
        with:
          webdav_address: https://apidocs-dav.quinimbus.cloud
          webdav_username: ${{secrets.apidocs_dav_user}}
          webdav_password: ${{secrets.apidocs_dav_pass}}
          webdav_upload_path: "/Persistence/SNAPSHOT/"
          files: "./target/site/apidocs/**"
          files_base: "./target/site/apidocs/"