name: test-build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 5.0
          mongodb-username: mongoroot
          mongodb-password: mongorootpassword
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Extract Project version
        id: project
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Build with Maven
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode --update-snapshots verify